name: Create PR from master to develop for non-web submissions

on:
  pull_request:
    types: [closed]
    branches:
      - master

permissions:
  contents: write

jobs:
  create-pr:
    if: >
      github.event.pull_request.merged == true && 
      !(startsWith(github.event.pull_request.head.ref, 'web_submission_') && 
      contains(github.event.pull_request.title, 'brain-score.org submission'))
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the 'master' branch
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history
          ref: master

      # Step 2: Create Pull Request to merge 'master' into 'develop'
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Sync master into develop"
          title: "Sync master into develop"
          body: "This PR syncs the latest changes from the master branch into the develop branch."
          base: develop  # Target branch for the PR
          branch: develop-sync-${{ github.run_id }}  # Use GitHub Actions run ID for a unique branch name
