name: Create PR from master to develop for non-web submissions

on:
  pull_request:
    types: [ closed ]
    branches:
      - master

permissions:
  contents: write

jobs:
  create-pr:
    if: >
      github.event.pull_request.merged == true && 
      !(startsWith(github.event.pull_request.head.ref, 'web_submission_') && 
      contains(github.event.pull_request.title, 'brain-score.org submission'))
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the 'develop' branch
      - uses: actions/checkout@v4
        with:
          ref: develop

      # Step 2: Reset 'develop' to match 'master'
      - name: Reset develop branch to match master
        run: |
          git fetch origin master:master
          git reset --hard master

      # Step 3: Create Pull Request to update 'develop'
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update develop branch with changes from master"
          title: "Sync master with develop"
          body: "This PR syncs the latest changes from the master branch into the develop branch."
          base: develop  # Target branch for the PR
          branch: develop-sync-$(date +%s)  # New branch name for the PR