name: Create PR from master to develop for non-web submissions

on:
  pull_request:
    types: [ closed ]
    branches:
      - master

permissions:
  contents: write

jobs:
  create-pr:
    if: >
      github.event.pull_request.merged == true && 
      !(startsWith(github.event.pull_request.head.ref, 'web_submission_') && 
      contains(github.event.pull_request.title, 'brain-score.org submission'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure Develop is Up to Date
        run: |
          git fetch origin
          git checkout develop
          git reset --hard origin/develop

      - name: Ensure Master is Up to Date
        run: |
          git fetch origin
          git checkout master
          git reset --hard origin/master

      - name: Check Differences Between Master and Develop
        run: |
          git fetch origin
          echo "Differences between master and develop:"
          git log origin/develop..origin/master --oneline

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: develop-PR
          base: develop
          title: Sync master with develop
          body: This PR syncs changes from master to develop for non-web submissions. Please review before merging.