name: Create PR from master to develop for non-web submissions

on:
  pull_request:
    types: [ closed ]
    branches:
      - master

permissions:
  contents: write

jobs:
  create-pr:
    if: >
      github.event.pull_request.merged == true && 
      !(startsWith(github.event.pull_request.head.ref, 'web_submission_') && 
      contains(github.event.pull_request.title, 'brain-score.org submission'))
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the 'develop' branch
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history
          ref: develop

      # Step 2: Merge 'master' into 'develop'
      - name: Merge master into develop
        run: |
          git fetch origin
          git checkout develop
          git merge origin/master

      # Step 3: Push the changes (if merge is successful)
      - name: Push changes to develop
        if: success()
        run: |
          git push origin develop

      # Step 4: Handle merge conflicts and create PR if needed
      - name: Create Pull Request if conflicts
        if: failure()  # This runs if the merge step fails (indicating conflicts)
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Merge master into develop with conflict resolution"
          title: "Resolve conflicts between master and develop"
          body: "This PR resolves merge conflicts between master and develop."
          base: develop
          branch: develop-merge-$(date +%s)