name: Sync develop with master

on:
  pull_request:
    types: [closed]
    branches:
      - master

permissions:
  contents: write

jobs:
  start:
    name: "Starting-🤞"
    runs-on: ubuntu-latest
    steps:
      - name: Starting
        id : init
        run: |
          echo "Starting branch synchronization of ${{ github.repository }}"

  create_pr_for_nonplugin:
    if: >
      github.event.pull_request.merged == true && 
      !(startsWith(github.event.pull_request.head.ref, 'web_submission_') && 
      contains(github.event.pull_request.title, 'brain-score.org submission'))
    runs-on: ubuntu-latest
    steps:
      - name: Check out the develop branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history
          ref: develop

      - name: Reset the develop branch
        run: |
          git fetch origin master
          git reset --hard origin/master

      - name: Create pull request in develop
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PAT }} # Expires after a year.
          commit-message: "Sync master into develop"
          title: "Sync master into develop"
          body: "This PR syncs the latest changes from the master branch into the develop branch."
          base: develop  # Target branch for the PR
          branch: developer-sync-pr-${{ github.run_id }}  # Use GitHub Actions run ID for a unique branch name

  auto_sync_for_plugin:
    if: >
      github.event.pull_request.merged == true && 
      startsWith(github.event.pull_request.head.ref, 'web_submission_') && 
      contains(github.event.pull_request.title, 'brain-score.org submission')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the develop branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history
          ref: develop

      - name: Configure Git user
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Attempt to Merge master into develop
        id: merge
        run: |
          git fetch origin master
          git checkout develop
          git merge origin/master || {
            if git diff --name-only --diff-filter=U | grep -q '.'; then
              echo "Merge conflict detected"
              echo "::set-output name=merge_conflict::true"
            else
              echo "Merge failed due to another reason"
              exit 1
            fi
          }

      - name: Push changes to develop (if merge is successful)
        if: steps.merge.outcome == 'success'
        run: |
          git push origin develop

      - name: Create pull request for merge conflicts
        if: steps.merge.outputs.merge_conflict == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PAT }}
          commit-message: "Merge master into develop with conflict resolution"
          title: "Resolve conflicts between master and develop"
          body: "This PR resolves merge conflicts between master and develop."
          base: develop
          branch: developer-sync-pr-conflict-${{ github.event.pull_request.number }}

      - name: Handle other merge failures
        if: failure() && steps.merge.outputs.merge_conflict != 'true'
        run: |
          echo "Handle non-conflict related failure, such as network issues or missing branches"
          # Possibly incorporate other additional handling logic here (E.g., like sending a notification or retrying the action)