name: Sync develop with master after web submissions

on:
  pull_request:
    types: [closed]
    branches:
      - master

permissions:
  contents: write

jobs:
  sync-developer:
    if: >
      github.event.pull_request.merged == true && 
      startsWith(github.event.pull_request.head.ref, 'web_submission_') && 
      contains(github.event.pull_request.title, 'brain-score.org submission')
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the 'develop' branch
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history
          ref: develop

      # Step 1.5: Configure Git user
      - name: Configure Git user
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      # Step 2: Merge 'master' into 'develop'
      - name: Merge master into develop
        run: |
          git fetch origin master
          git checkout develop
          git merge origin/master

      # Step 3: Push the changes (if merge is successful)
      - name: Push changes to develop
        if: success()
        run: |
          git push origin develop

      # Step 4: Handle merge conflicts and create PR if needed
      - name: Create Pull Request if conflicts
        if: failure()  # This runs if the merge step fails (indicating conflicts)
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PAT }}
          commit-message: "Merge master into develop with conflict resolution"
          title: "Resolve conflicts between master and develop"
          body: "This PR resolves merge conflicts between master and develop."
          base: develop
          branch: develop-sync-${{ github.run_id }}  # Use GitHub Actions run ID for a unique branch name
